server:
  port:
     8080
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/ucar_develop?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowMultiQueries=true&serverTimezone=GMT%2B8&&zeroDateTimeBehavior=convertToNull
      username: root
      password: jingan
      driver-class-name: com.mysql.cj.jdbc.Driver